name: understanding_rect_from_left_top_right_bottom
description: "A Flutter application demonstrating the use of Rect.fromLTRB."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

homepage: https://github.com/JSimonDev/understanding_rect_from_left_top_right_bottom
repository: https://github.com/JSimonDev/understanding_rect_from_left_top_right_bottom
issue_tracker: https://github.com/JSimonDev/understanding_rect_from_left_top_right_bottom/issues
